export interface StockInfo {
  name: string;
  exchange: "NYSE" | "NASDAQ" | "SET";
}

// Key: ticker symbol (e.g. "AAPL", "PTT.BK")
// SET tickers use the ".BK" suffix.
// Only entries with high-confidence names and exchanges are listed here;
// unknown tickers fall back to the Finnhub search API at runtime.
export const STOCK_INFO: Readonly<Record<string, StockInfo>> = {
  // ── NASDAQ-listed ──────────────────────────────────────────────────────────
  AAPL:  { name: "Apple Inc.",                               exchange: "NASDAQ" },
  MSFT:  { name: "Microsoft Corporation",                    exchange: "NASDAQ" },
  NVDA:  { name: "NVIDIA Corporation",                       exchange: "NASDAQ" },
  AMZN:  { name: "Amazon.com Inc.",                          exchange: "NASDAQ" },
  META:  { name: "Meta Platforms Inc.",                      exchange: "NASDAQ" },
  GOOGL: { name: "Alphabet Inc. (Class A)",                  exchange: "NASDAQ" },
  GOOG:  { name: "Alphabet Inc. (Class C)",                  exchange: "NASDAQ" },
  TSLA:  { name: "Tesla Inc.",                               exchange: "NASDAQ" },
  AVGO:  { name: "Broadcom Inc.",                            exchange: "NASDAQ" },
  COST:  { name: "Costco Wholesale Corporation",             exchange: "NASDAQ" },
  NFLX:  { name: "Netflix Inc.",                             exchange: "NASDAQ" },
  ADBE:  { name: "Adobe Inc.",                               exchange: "NASDAQ" },
  AMD:   { name: "Advanced Micro Devices Inc.",              exchange: "NASDAQ" },
  QCOM:  { name: "Qualcomm Incorporated",                    exchange: "NASDAQ" },
  INTU:  { name: "Intuit Inc.",                              exchange: "NASDAQ" },
  CSCO:  { name: "Cisco Systems Inc.",                       exchange: "NASDAQ" },
  TXN:   { name: "Texas Instruments Incorporated",           exchange: "NASDAQ" },
  AMAT:  { name: "Applied Materials Inc.",                   exchange: "NASDAQ" },
  MU:    { name: "Micron Technology Inc.",                   exchange: "NASDAQ" },
  LRCX:  { name: "Lam Research Corporation",                 exchange: "NASDAQ" },
  KLAC:  { name: "KLA Corporation",                          exchange: "NASDAQ" },
  SNPS:  { name: "Synopsys Inc.",                            exchange: "NASDAQ" },
  CDNS:  { name: "Cadence Design Systems Inc.",              exchange: "NASDAQ" },
  MCHP:  { name: "Microchip Technology Inc.",                exchange: "NASDAQ" },
  ADI:   { name: "Analog Devices Inc.",                      exchange: "NASDAQ" },
  ASML:  { name: "ASML Holding N.V.",                        exchange: "NASDAQ" },
  FTNT:  { name: "Fortinet Inc.",                            exchange: "NASDAQ" },
  MRVL:  { name: "Marvell Technology Inc.",                  exchange: "NASDAQ" },
  PANW:  { name: "Palo Alto Networks Inc.",                  exchange: "NASDAQ" },
  CRWD:  { name: "CrowdStrike Holdings Inc.",                exchange: "NASDAQ" },
  WDAY:  { name: "Workday Inc.",                             exchange: "NASDAQ" },
  ZS:    { name: "Zscaler Inc.",                             exchange: "NASDAQ" },
  DDOG:  { name: "Datadog Inc.",                             exchange: "NASDAQ" },
  ABNB:  { name: "Airbnb Inc.",                              exchange: "NASDAQ" },
  TEAM:  { name: "Atlassian Corporation",                    exchange: "NASDAQ" },
  ON:    { name: "ON Semiconductor Corporation",             exchange: "NASDAQ" },
  TTD:   { name: "The Trade Desk Inc.",                      exchange: "NASDAQ" },
  ANSS:  { name: "ANSYS Inc.",                               exchange: "NASDAQ" },
  SMCI:  { name: "Super Micro Computer Inc.",                exchange: "NASDAQ" },
  AMGN:  { name: "Amgen Inc.",                               exchange: "NASDAQ" },
  ISRG:  { name: "Intuitive Surgical Inc.",                  exchange: "NASDAQ" },
  VRTX:  { name: "Vertex Pharmaceuticals Inc.",              exchange: "NASDAQ" },
  REGN:  { name: "Regeneron Pharmaceuticals Inc.",           exchange: "NASDAQ" },
  BIIB:  { name: "Biogen Inc.",                              exchange: "NASDAQ" },
  GILD:  { name: "Gilead Sciences Inc.",                     exchange: "NASDAQ" },
  IDXX:  { name: "IDEXX Laboratories Inc.",                  exchange: "NASDAQ" },
  DXCM:  { name: "DexCom Inc.",                              exchange: "NASDAQ" },
  MRNA:  { name: "Moderna Inc.",                             exchange: "NASDAQ" },
  GEHC:  { name: "GE HealthCare Technologies Inc.",          exchange: "NASDAQ" },
  ORLY:  { name: "O'Reilly Automotive Inc.",                 exchange: "NASDAQ" },
  ROST:  { name: "Ross Stores Inc.",                         exchange: "NASDAQ" },
  BKNG:  { name: "Booking Holdings Inc.",                    exchange: "NASDAQ" },
  SBUX:  { name: "Starbucks Corporation",                    exchange: "NASDAQ" },
  LULU:  { name: "Lululemon Athletica Inc.",                 exchange: "NASDAQ" },
  DLTR:  { name: "Dollar Tree Inc.",                         exchange: "NASDAQ" },
  MNST:  { name: "Monster Beverage Corporation",             exchange: "NASDAQ" },
  PEP:   { name: "PepsiCo Inc.",                             exchange: "NASDAQ" },
  MDLZ:  { name: "Mondelez International Inc.",              exchange: "NASDAQ" },
  KHC:   { name: "The Kraft Heinz Company",                  exchange: "NASDAQ" },
  ADP:   { name: "Automatic Data Processing Inc.",           exchange: "NASDAQ" },
  PAYX:  { name: "Paychex Inc.",                             exchange: "NASDAQ" },
  CTAS:  { name: "Cintas Corporation",                       exchange: "NASDAQ" },
  ODFL:  { name: "Old Dominion Freight Line Inc.",           exchange: "NASDAQ" },
  FAST:  { name: "Fastenal Company",                         exchange: "NASDAQ" },
  CPRT:  { name: "Copart Inc.",                              exchange: "NASDAQ" },
  PCAR:  { name: "PACCAR Inc.",                              exchange: "NASDAQ" },
  CTSH:  { name: "Cognizant Technology Solutions",           exchange: "NASDAQ" },
  VRSK:  { name: "Verisk Analytics Inc.",                    exchange: "NASDAQ" },
  CDW:   { name: "CDW Corporation",                          exchange: "NASDAQ" },
  CMCSA: { name: "Comcast Corporation",                      exchange: "NASDAQ" },
  EA:    { name: "Electronic Arts Inc.",                     exchange: "NASDAQ" },
  TTWO:  { name: "Take-Two Interactive Software",            exchange: "NASDAQ" },
  TMUS:  { name: "T-Mobile US Inc.",                         exchange: "NASDAQ" },
  CEG:   { name: "Constellation Energy Corporation",         exchange: "NASDAQ" },
  FANG:  { name: "Diamondback Energy Inc.",                  exchange: "NASDAQ" },
  PYPL:  { name: "PayPal Holdings Inc.",                     exchange: "NASDAQ" },
  PLTR:  { name: "Palantir Technologies Inc.",               exchange: "NASDAQ" },
  APP:   { name: "AppLovin Corporation",                     exchange: "NASDAQ" },
  AXON:  { name: "Axon Enterprise Inc.",                     exchange: "NASDAQ" },
  MSTR:  { name: "MicroStrategy Incorporated",               exchange: "NASDAQ" },
  COIN:  { name: "Coinbase Global Inc.",                     exchange: "NASDAQ" },
  MELI:  { name: "MercadoLibre Inc.",                        exchange: "NASDAQ" },
  PDD:   { name: "PDD Holdings Inc.",                        exchange: "NASDAQ" },
  NXPI:  { name: "NXP Semiconductors N.V.",                  exchange: "NASDAQ" },
  ILMN:  { name: "Illumina Inc.",                            exchange: "NASDAQ" },
  SIRI:  { name: "Sirius XM Holdings Inc.",                  exchange: "NASDAQ" },
  BIDU:  { name: "Baidu Inc.",                               exchange: "NASDAQ" },
  JD:    { name: "JD.com Inc.",                              exchange: "NASDAQ" },
  NTES:  { name: "NetEase Inc.",                             exchange: "NASDAQ" },
  GFS:   { name: "GlobalFoundries Inc.",                     exchange: "NASDAQ" },
  NTRS:  { name: "Northern Trust Corporation",               exchange: "NASDAQ" },
  CME:   { name: "CME Group Inc.",                           exchange: "NASDAQ" },
  HON:   { name: "Honeywell International Inc.",             exchange: "NASDAQ" },
  CSX:   { name: "CSX Corporation",                          exchange: "NASDAQ" },
  MAR:   { name: "Marriott International Inc.",              exchange: "NASDAQ" },
  EBAY:  { name: "eBay Inc.",                                exchange: "NASDAQ" },
  ETSY:  { name: "Etsy Inc.",                                exchange: "NASDAQ" },
  CHTR:  { name: "Charter Communications Inc.",              exchange: "NASDAQ" },
  EQIX:  { name: "Equinix Inc.",                             exchange: "NASDAQ" },
  AEP:   { name: "American Electric Power Company",          exchange: "NASDAQ" },
  EXC:   { name: "Exelon Corporation",                       exchange: "NASDAQ" },
  ENPH:  { name: "Enphase Energy Inc.",                      exchange: "NASDAQ" },
  FSLR:  { name: "First Solar Inc.",                         exchange: "NASDAQ" },
  HOOD:  { name: "Robinhood Markets Inc.",                   exchange: "NASDAQ" },
  SOFI:  { name: "SoFi Technologies Inc.",                   exchange: "NASDAQ" },
  AFRM:  { name: "Affirm Holdings Inc.",                     exchange: "NASDAQ" },
  RKLB:  { name: "Rocket Lab USA Inc.",                      exchange: "NASDAQ" },
  RGTI:  { name: "Rigetti Computing Inc.",                   exchange: "NASDAQ" },
  RIVN:  { name: "Rivian Automotive Inc.",                   exchange: "NASDAQ" },
  LCID:  { name: "Lucid Group Inc.",                         exchange: "NASDAQ" },

  // ── NYSE-listed ────────────────────────────────────────────────────────────
  JPM:   { name: "JPMorgan Chase & Co.",                     exchange: "NYSE" },
  BAC:   { name: "Bank of America Corporation",              exchange: "NYSE" },
  WFC:   { name: "Wells Fargo & Company",                    exchange: "NYSE" },
  GS:    { name: "The Goldman Sachs Group Inc.",             exchange: "NYSE" },
  MS:    { name: "Morgan Stanley",                           exchange: "NYSE" },
  C:     { name: "Citigroup Inc.",                           exchange: "NYSE" },
  USB:   { name: "U.S. Bancorp",                             exchange: "NYSE" },
  TFC:   { name: "Truist Financial Corporation",             exchange: "NYSE" },
  PNC:   { name: "PNC Financial Services Group",             exchange: "NYSE" },
  COF:   { name: "Capital One Financial Corporation",        exchange: "NYSE" },
  AXP:   { name: "American Express Company",                 exchange: "NYSE" },
  BK:    { name: "The Bank of New York Mellon",              exchange: "NYSE" },
  STT:   { name: "State Street Corporation",                 exchange: "NYSE" },
  SCHW:  { name: "The Charles Schwab Corporation",           exchange: "NYSE" },
  BLK:   { name: "BlackRock Inc.",                           exchange: "NYSE" },
  KKR:   { name: "KKR & Co. Inc.",                           exchange: "NYSE" },
  BX:    { name: "Blackstone Inc.",                          exchange: "NYSE" },
  APO:   { name: "Apollo Global Management Inc.",            exchange: "NYSE" },
  ICE:   { name: "Intercontinental Exchange Inc.",           exchange: "NYSE" },
  SPGI:  { name: "S&P Global Inc.",                          exchange: "NYSE" },
  MCO:   { name: "Moody's Corporation",                      exchange: "NYSE" },
  V:     { name: "Visa Inc.",                                exchange: "NYSE" },
  MA:    { name: "Mastercard Incorporated",                  exchange: "NYSE" },
  MMC:   { name: "Marsh & McLennan Companies",               exchange: "NYSE" },
  AON:   { name: "Aon plc",                                  exchange: "NYSE" },
  AIG:   { name: "American International Group",             exchange: "NYSE" },
  MET:   { name: "MetLife Inc.",                             exchange: "NYSE" },
  PRU:   { name: "Prudential Financial Inc.",                exchange: "NYSE" },
  AFL:   { name: "Aflac Incorporated",                       exchange: "NYSE" },
  ALL:   { name: "The Allstate Corporation",                 exchange: "NYSE" },
  TRV:   { name: "The Travelers Companies Inc.",             exchange: "NYSE" },
  HIG:   { name: "The Hartford Financial Services",          exchange: "NYSE" },
  CB:    { name: "Chubb Limited",                            exchange: "NYSE" },
  UNH:   { name: "UnitedHealth Group Incorporated",          exchange: "NYSE" },
  JNJ:   { name: "Johnson & Johnson",                        exchange: "NYSE" },
  LLY:   { name: "Eli Lilly and Company",                    exchange: "NYSE" },
  ABT:   { name: "Abbott Laboratories",                      exchange: "NYSE" },
  MRK:   { name: "Merck & Co. Inc.",                         exchange: "NYSE" },
  PFE:   { name: "Pfizer Inc.",                              exchange: "NYSE" },
  ABBV:  { name: "AbbVie Inc.",                              exchange: "NYSE" },
  TMO:   { name: "Thermo Fisher Scientific Inc.",            exchange: "NYSE" },
  BMY:   { name: "Bristol-Myers Squibb Company",             exchange: "NYSE" },
  MDT:   { name: "Medtronic plc",                            exchange: "NYSE" },
  BSX:   { name: "Boston Scientific Corporation",            exchange: "NYSE" },
  ZTS:   { name: "Zoetis Inc.",                              exchange: "NYSE" },
  EW:    { name: "Edwards Lifesciences Corporation",         exchange: "NYSE" },
  DHR:   { name: "Danaher Corporation",                      exchange: "NYSE" },
  STE:   { name: "STERIS plc",                               exchange: "NYSE" },
  IQV:   { name: "IQVIA Holdings Inc.",                      exchange: "NYSE" },
  HCA:   { name: "HCA Healthcare Inc.",                      exchange: "NYSE" },
  CI:    { name: "The Cigna Group",                          exchange: "NYSE" },
  ELV:   { name: "Elevance Health Inc.",                     exchange: "NYSE" },
  MOH:   { name: "Molina Healthcare Inc.",                   exchange: "NYSE" },
  HUM:   { name: "Humana Inc.",                              exchange: "NYSE" },
  CVS:   { name: "CVS Health Corporation",                   exchange: "NYSE" },
  MCK:   { name: "McKesson Corporation",                     exchange: "NYSE" },
  GE:    { name: "GE Aerospace",                             exchange: "NYSE" },
  CAT:   { name: "Caterpillar Inc.",                         exchange: "NYSE" },
  DE:    { name: "Deere & Company",                          exchange: "NYSE" },
  UPS:   { name: "United Parcel Service Inc.",               exchange: "NYSE" },
  FDX:   { name: "FedEx Corporation",                        exchange: "NYSE" },
  RTX:   { name: "RTX Corporation",                          exchange: "NYSE" },
  LMT:   { name: "Lockheed Martin Corporation",              exchange: "NYSE" },
  NOC:   { name: "Northrop Grumman Corporation",             exchange: "NYSE" },
  GD:    { name: "General Dynamics Corporation",             exchange: "NYSE" },
  BA:    { name: "The Boeing Company",                       exchange: "NYSE" },
  MMM:   { name: "3M Company",                               exchange: "NYSE" },
  ETN:   { name: "Eaton Corporation plc",                    exchange: "NYSE" },
  EMR:   { name: "Emerson Electric Co.",                     exchange: "NYSE" },
  ITW:   { name: "Illinois Tool Works Inc.",                 exchange: "NYSE" },
  PH:    { name: "Parker-Hannifin Corporation",              exchange: "NYSE" },
  GWW:   { name: "W.W. Grainger Inc.",                       exchange: "NYSE" },
  OTIS:  { name: "Otis Worldwide Corporation",               exchange: "NYSE" },
  UNP:   { name: "Union Pacific Corporation",                exchange: "NYSE" },
  NSC:   { name: "Norfolk Southern Corporation",             exchange: "NYSE" },
  URI:   { name: "United Rentals Inc.",                      exchange: "NYSE" },
  WM:    { name: "Waste Management Inc.",                    exchange: "NYSE" },
  RSG:   { name: "Republic Services Inc.",                   exchange: "NYSE" },
  LHX:   { name: "L3Harris Technologies Inc.",               exchange: "NYSE" },
  TT:    { name: "Trane Technologies plc",                   exchange: "NYSE" },
  TDG:   { name: "TransDigm Group Incorporated",             exchange: "NYSE" },
  UBER:  { name: "Uber Technologies Inc.",                   exchange: "NYSE" },
  DASH:  { name: "DoorDash Inc.",                            exchange: "NYSE" },
  XOM:   { name: "Exxon Mobil Corporation",                  exchange: "NYSE" },
  CVX:   { name: "Chevron Corporation",                      exchange: "NYSE" },
  COP:   { name: "ConocoPhillips",                           exchange: "NYSE" },
  EOG:   { name: "EOG Resources Inc.",                       exchange: "NYSE" },
  SLB:   { name: "SLB (Schlumberger)",                       exchange: "NYSE" },
  OXY:   { name: "Occidental Petroleum Corporation",         exchange: "NYSE" },
  MPC:   { name: "Marathon Petroleum Corporation",           exchange: "NYSE" },
  VLO:   { name: "Valero Energy Corporation",                exchange: "NYSE" },
  WMT:   { name: "Walmart Inc.",                             exchange: "NYSE" },
  PG:    { name: "Procter & Gamble Company",                 exchange: "NYSE" },
  KO:    { name: "The Coca-Cola Company",                    exchange: "NYSE" },
  PM:    { name: "Philip Morris International",              exchange: "NYSE" },
  MO:    { name: "Altria Group Inc.",                        exchange: "NYSE" },
  CL:    { name: "Colgate-Palmolive Company",                exchange: "NYSE" },
  GIS:   { name: "General Mills Inc.",                       exchange: "NYSE" },
  TSN:   { name: "Tyson Foods Inc.",                         exchange: "NYSE" },
  CLX:   { name: "The Clorox Company",                       exchange: "NYSE" },
  SYY:   { name: "Sysco Corporation",                        exchange: "NYSE" },
  HD:    { name: "The Home Depot Inc.",                      exchange: "NYSE" },
  MCD:   { name: "McDonald's Corporation",                   exchange: "NYSE" },
  NKE:   { name: "NIKE Inc.",                                exchange: "NYSE" },
  LOW:   { name: "Lowe's Companies Inc.",                    exchange: "NYSE" },
  TJX:   { name: "The TJX Companies Inc.",                   exchange: "NYSE" },
  RCL:   { name: "Royal Caribbean Cruises Ltd.",             exchange: "NYSE" },
  HLT:   { name: "Hilton Worldwide Holdings",                exchange: "NYSE" },
  CMG:   { name: "Chipotle Mexican Grill Inc.",              exchange: "NYSE" },
  F:     { name: "Ford Motor Company",                       exchange: "NYSE" },
  GM:    { name: "General Motors Company",                   exchange: "NYSE" },
  TGT:   { name: "Target Corporation",                       exchange: "NYSE" },
  DIS:   { name: "The Walt Disney Company",                  exchange: "NYSE" },
  T:     { name: "AT&T Inc.",                                exchange: "NYSE" },
  VZ:    { name: "Verizon Communications Inc.",              exchange: "NYSE" },
  LIN:   { name: "Linde plc",                                exchange: "NYSE" },
  APD:   { name: "Air Products and Chemicals Inc.",          exchange: "NYSE" },
  ECL:   { name: "Ecolab Inc.",                              exchange: "NYSE" },
  SHW:   { name: "The Sherwin-Williams Company",             exchange: "NYSE" },
  FCX:   { name: "Freeport-McMoRan Inc.",                    exchange: "NYSE" },
  NUE:   { name: "Nucor Corporation",                        exchange: "NYSE" },
  DOW:   { name: "Dow Inc.",                                 exchange: "NYSE" },
  DD:    { name: "DuPont de Nemours Inc.",                   exchange: "NYSE" },
  PLD:   { name: "Prologis Inc.",                            exchange: "NYSE" },
  AMT:   { name: "American Tower Corporation",               exchange: "NYSE" },
  CCI:   { name: "Crown Castle Inc.",                        exchange: "NYSE" },
  SPG:   { name: "Simon Property Group Inc.",                exchange: "NYSE" },
  DLR:   { name: "Digital Realty Trust Inc.",                exchange: "NYSE" },
  PSA:   { name: "Public Storage",                           exchange: "NYSE" },
  WELL:  { name: "Welltower Inc.",                           exchange: "NYSE" },
  NEE:   { name: "NextEra Energy Inc.",                      exchange: "NYSE" },
  SO:    { name: "The Southern Company",                     exchange: "NYSE" },
  DUK:   { name: "Duke Energy Corporation",                  exchange: "NYSE" },
  PCG:   { name: "PG&E Corporation",                         exchange: "NYSE" },
  SRE:   { name: "Sempra",                                   exchange: "NYSE" },
  D:     { name: "Dominion Energy Inc.",                     exchange: "NYSE" },
  ORCL:  { name: "Oracle Corporation",                       exchange: "NYSE" },
  IBM:   { name: "IBM Corporation",                          exchange: "NYSE" },
  ACN:   { name: "Accenture plc",                            exchange: "NYSE" },
  CRM:   { name: "Salesforce Inc.",                          exchange: "NYSE" },
  NOW:   { name: "ServiceNow Inc.",                          exchange: "NYSE" },
  HPQ:   { name: "HP Inc.",                                  exchange: "NYSE" },
  HPE:   { name: "Hewlett Packard Enterprise",               exchange: "NYSE" },
  DELL:  { name: "Dell Technologies Inc.",                   exchange: "NYSE" },
  GEV:   { name: "GE Vernova Inc.",                          exchange: "NYSE" },
  VST:   { name: "Vistra Corp.",                             exchange: "NYSE" },
  SOLV:  { name: "Solventum Corporation",                    exchange: "NYSE" },
  TKO:   { name: "TKO Group Holdings Inc.",                  exchange: "NYSE" },
  IONQ:  { name: "IonQ Inc.",                                exchange: "NYSE" },
  JOBY:  { name: "Joby Aviation Inc.",                       exchange: "NYSE" },
  QBTS:  { name: "D-Wave Quantum Inc.",                      exchange: "NYSE" },
  HIMS:  { name: "Hims & Hers Health Inc.",                  exchange: "NYSE" },

  // ── SET100 — Stock Exchange of Thailand (.BK suffix) ──────────────────────
  "ADVANC.BK": { name: "Advanced Info Service PCL",              exchange: "SET" },
  "AOT.BK":    { name: "Airports of Thailand PCL",               exchange: "SET" },
  "AP.BK":     { name: "AP (Thailand) PCL",                      exchange: "SET" },
  "AWC.BK":    { name: "Asset World Corp PCL",                   exchange: "SET" },
  "BANPU.BK":  { name: "Banpu PCL",                              exchange: "SET" },
  "BAY.BK":    { name: "Bank of Ayudhya PCL (Krungsri)",         exchange: "SET" },
  "BBL.BK":    { name: "Bangkok Bank PCL",                       exchange: "SET" },
  "BCH.BK":    { name: "Bangkok Chain Hospital PCL",             exchange: "SET" },
  "BDMS.BK":   { name: "Bangkok Dusit Medical Services PCL",     exchange: "SET" },
  "BEM.BK":    { name: "Bangkok Expressway and Metro PCL",       exchange: "SET" },
  "BH.BK":     { name: "Bumrungrad Hospital PCL",                exchange: "SET" },
  "BGRIM.BK":  { name: "B.Grimm Power PCL",                      exchange: "SET" },
  "BJC.BK":    { name: "Berli Jucker PCL",                       exchange: "SET" },
  "BLA.BK":    { name: "Bangkok Life Assurance PCL",             exchange: "SET" },
  "BTS.BK":    { name: "BTS Group Holdings PCL",                 exchange: "SET" },
  "CBG.BK":    { name: "Carabao Group PCL",                      exchange: "SET" },
  "CENTEL.BK": { name: "Central Plaza Hotel PCL",                exchange: "SET" },
  "CPAXT.BK":  { name: "CP Axtra PCL (Makro)",                   exchange: "SET" },
  "CPALL.BK":  { name: "CP ALL PCL (7-Eleven Thailand)",         exchange: "SET" },
  "CPF.BK":    { name: "Charoen Pokphand Foods PCL",             exchange: "SET" },
  "CPN.BK":    { name: "Central Pattana PCL",                    exchange: "SET" },
  "CRC.BK":    { name: "Central Retail Corporation PCL",         exchange: "SET" },
  "DELTA.BK":  { name: "Delta Electronics (Thailand) PCL",       exchange: "SET" },
  "EA.BK":     { name: "Energy Absolute PCL",                    exchange: "SET" },
  "EGCO.BK":   { name: "Electricity Generating PCL",             exchange: "SET" },
  "GLOBAL.BK": { name: "Siam Global House PCL",                  exchange: "SET" },
  "GPSC.BK":   { name: "Global Power Synergy PCL",               exchange: "SET" },
  "GULF.BK":   { name: "Gulf Energy Development PCL",            exchange: "SET" },
  "HANA.BK":   { name: "Hana Microelectronics PCL",              exchange: "SET" },
  "HMPRO.BK":  { name: "Home Product Center PCL",                exchange: "SET" },
  "INTUCH.BK": { name: "Intouch Holdings PCL",                   exchange: "SET" },
  "IVL.BK":    { name: "Indorama Ventures PCL",                  exchange: "SET" },
  "JMT.BK":    { name: "JMT Network Services PCL",               exchange: "SET" },
  "KBANK.BK":  { name: "Kasikorn Bank PCL",                      exchange: "SET" },
  "KCE.BK":    { name: "KCE Electronics PCL",                    exchange: "SET" },
  "KKP.BK":    { name: "Kiatnakin Phatra Financial Group PCL",   exchange: "SET" },
  "KTB.BK":    { name: "Krungthai Bank PCL",                     exchange: "SET" },
  "LH.BK":     { name: "Land and Houses PCL",                    exchange: "SET" },
  "LHFG.BK":   { name: "LH Financial Group PCL",                 exchange: "SET" },
  "MAJOR.BK":  { name: "Major Cineplex Group PCL",               exchange: "SET" },
  "MBK.BK":    { name: "MBK PCL",                                exchange: "SET" },
  "MINT.BK":   { name: "Minor International PCL",                exchange: "SET" },
  "MTC.BK":    { name: "Muangthai Capital PCL",                  exchange: "SET" },
  "OR.BK":     { name: "PTT Oil and Retail Business PCL",        exchange: "SET" },
  "OSP.BK":    { name: "Osotspa PCL",                            exchange: "SET" },
  "PSH.BK":    { name: "Pruksa Holding PCL",                     exchange: "SET" },
  "PTT.BK":    { name: "PTT PCL",                                exchange: "SET" },
  "PTTEP.BK":  { name: "PTT Exploration and Production PCL",     exchange: "SET" },
  "PTTGC.BK":  { name: "PTT Global Chemical PCL",                exchange: "SET" },
  "QH.BK":     { name: "Quality Houses PCL",                     exchange: "SET" },
  "RATCH.BK":  { name: "Ratch Group PCL",                        exchange: "SET" },
  "SCB.BK":    { name: "The Siam Commercial Bank PCL",           exchange: "SET" },
  "SCC.BK":    { name: "Siam Cement PCL",                        exchange: "SET" },
  "SIRI.BK":   { name: "Siri Venture PCL",                       exchange: "SET" },
  "SPALI.BK":  { name: "Supalai PCL",                            exchange: "SET" },
  "STA.BK":    { name: "Sri Trang Agro-Industry PCL",            exchange: "SET" },
  "STEC.BK":   { name: "Sino-Thai Engineering PCL",              exchange: "SET" },
  "STGT.BK":   { name: "Sri Trang Gloves (Thailand) PCL",        exchange: "SET" },
  "SUPER.BK":  { name: "Superblock PCL",                         exchange: "SET" },
  "TCAP.BK":   { name: "Thanachart Capital PCL",                 exchange: "SET" },
  "TIDLOR.BK": { name: "Ngern Tid Lor PCL",                      exchange: "SET" },
  "TISCO.BK":  { name: "TISCO Financial Group PCL",              exchange: "SET" },
  "TOP.BK":    { name: "Thai Oil PCL",                           exchange: "SET" },
  "TQM.BK":    { name: "TQM Alpha PCL",                          exchange: "SET" },
  "TRUE.BK":   { name: "True Corporation PCL",                   exchange: "SET" },
  "TU.BK":     { name: "Thai Union Group PCL",                   exchange: "SET" },
  "TTB.BK":    { name: "TMBThanachart Bank PCL",                 exchange: "SET" },
  "VGI.BK":    { name: "VGI PCL",                                exchange: "SET" },
  "WHA.BK":    { name: "WHA Corporation PCL",                    exchange: "SET" },
} satisfies Record<string, StockInfo>;
