/**
 * Comprehensive stock catalog — static data, no API calls.
 * Covers: full S&P 500 (503), Nasdaq 100 extras, Dow 30, major ETFs, major ADRs,
 * and a selection of well-known US mid-caps.
 *
 * Each entry: ticker, name, exchange, sector (GICS short), indices membership.
 * Prices are never stored here — fetch on demand via the quote API.
 *
 * Source notes:
 *  - S&P 500 constituents as of 2025-Q2 (update after quarterly rebalances)
 *  - Nasdaq 100 as of 2025-Q2
 *  - ETF list: iShares, Vanguard, SPDR, ARK, Invesco confirmed as of 2025
 *  - ADRs: only well-known, liquid names included; no obscure OTC tickers
 */

export interface CatalogEntry {
  ticker:   string;
  name:     string;
  exchange: "NYSE" | "NASDAQ" | "AMEX" | "SET" | "OTC" | "CBOE";
  sector:   string;   // GICS short form
  indices:  string[]; // e.g. ["SP500", "NASDAQ100", "DOW30"]
}

// ─── Raw data ─────────────────────────────────────────────────────────────────
// Sorted: SP500 (by sector) → Nasdaq extras → Dow additions → ETFs → ADRs → others

const RAW: readonly Omit<CatalogEntry, "ticker">[] & { 0: Omit<CatalogEntry, "ticker"> } = [] as never;

// We define it as a flat array keyed by ticker for fast lookup
const _entries: [string, Omit<CatalogEntry, "ticker">][] = [
  // ── Communication Services ─────────────────────────────────────────────────
  ["GOOGL", { name: "Alphabet Inc. Class A",         exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["GOOG",  { name: "Alphabet Inc. Class C",         exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["META",  { name: "Meta Platforms Inc.",            exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["NFLX",  { name: "Netflix Inc.",                  exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["DIS",   { name: "The Walt Disney Company",        exchange: "NYSE",   sector: "Comm",     indices: ["SP500","DOW30"] }],
  ["CMCSA", { name: "Comcast Corporation",            exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["T",     { name: "AT&T Inc.",                     exchange: "NYSE",   sector: "Comm",     indices: ["SP500"] }],
  ["VZ",    { name: "Verizon Communications Inc.",    exchange: "NYSE",   sector: "Comm",     indices: ["SP500","DOW30"] }],
  ["TMUS",  { name: "T-Mobile US Inc.",               exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["CHTR",  { name: "Charter Communications Inc.",    exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["WBD",   { name: "Warner Bros. Discovery Inc.",    exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["FOXA",  { name: "Fox Corporation Class A",        exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["FOX",   { name: "Fox Corporation Class B",        exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["NWSA",  { name: "News Corporation Class A",       exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["NWS",   { name: "News Corporation Class B",       exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["OMC",   { name: "Omnicom Group Inc.",             exchange: "NYSE",   sector: "Comm",     indices: ["SP500"] }],
  ["IPG",   { name: "Interpublic Group of Companies", exchange: "NYSE",   sector: "Comm",     indices: ["SP500"] }],
  ["LYV",   { name: "Live Nation Entertainment Inc.", exchange: "NYSE",   sector: "Comm",     indices: ["SP500"] }],
  ["EA",    { name: "Electronic Arts Inc.",           exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["TTWO",  { name: "Take-Two Interactive Software",  exchange: "NASDAQ", sector: "Comm",     indices: ["SP500","NASDAQ100"] }],
  ["PARA",  { name: "Paramount Global",               exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["MTCH",  { name: "Match Group Inc.",               exchange: "NASDAQ", sector: "Comm",     indices: ["SP500"] }],
  ["TKO",   { name: "TKO Group Holdings Inc.",        exchange: "NYSE",   sector: "Comm",     indices: ["SP500"] }],
  ["RBLX",  { name: "Roblox Corporation",             exchange: "NYSE",   sector: "Comm",     indices: [] }],
  ["SNAP",  { name: "Snap Inc.",                      exchange: "NYSE",   sector: "Comm",     indices: [] }],
  ["PINS",  { name: "Pinterest Inc.",                 exchange: "NYSE",   sector: "Comm",     indices: [] }],
  ["SPOT",  { name: "Spotify Technology S.A.",        exchange: "NYSE",   sector: "Comm",     indices: [] }],
  ["X",     { name: "X Corp (formerly Twitter)",      exchange: "NYSE",   sector: "Comm",     indices: [] }],

  // ── Consumer Discretionary ────────────────────────────────────────────────
  ["AMZN",  { name: "Amazon.com Inc.",               exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["TSLA",  { name: "Tesla Inc.",                    exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["HD",    { name: "The Home Depot Inc.",            exchange: "NYSE",   sector: "Consumer", indices: ["SP500","DOW30"] }],
  ["MCD",   { name: "McDonald's Corporation",         exchange: "NYSE",   sector: "Consumer", indices: ["SP500","DOW30"] }],
  ["BKNG",  { name: "Booking Holdings Inc.",          exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["NKE",   { name: "Nike Inc.",                     exchange: "NYSE",   sector: "Consumer", indices: ["SP500","DOW30"] }],
  ["LOW",   { name: "Lowe's Companies Inc.",          exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["TJX",   { name: "TJX Companies Inc.",             exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["SBUX",  { name: "Starbucks Corporation",          exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["RCL",   { name: "Royal Caribbean Cruises Ltd.",   exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["HLT",   { name: "Hilton Worldwide Holdings Inc.", exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["MAR",   { name: "Marriott International Inc.",    exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["ABNB",  { name: "Airbnb Inc.",                   exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["CMG",   { name: "Chipotle Mexican Grill Inc.",    exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["EBAY",  { name: "eBay Inc.",                     exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["F",     { name: "Ford Motor Company",             exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["GM",    { name: "General Motors Company",         exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["TGT",   { name: "Target Corporation",             exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["GRMN",  { name: "Garmin Ltd.",                   exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["ROST",  { name: "Ross Stores Inc.",               exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["ORLY",  { name: "O'Reilly Automotive Inc.",       exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["APTV",  { name: "Aptiv PLC",                     exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["AN",    { name: "AutoNation Inc.",                exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["KMX",   { name: "CarMax Inc.",                   exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["AZO",   { name: "AutoZone Inc.",                 exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["DLTR",  { name: "Dollar Tree Inc.",               exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["DG",    { name: "Dollar General Corporation",     exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["BBY",   { name: "Best Buy Co. Inc.",              exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["DPZ",   { name: "Domino's Pizza Inc.",            exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["NCLH",  { name: "Norwegian Cruise Line Holdings", exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["CCL",   { name: "Carnival Corporation",           exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["MGM",   { name: "MGM Resorts International",      exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["WYNN",  { name: "Wynn Resorts Ltd.",              exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["PHM",   { name: "PulteGroup Inc.",                exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["LEN",   { name: "Lennar Corporation",             exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["DHI",   { name: "D.R. Horton Inc.",               exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["TOL",   { name: "Toll Brothers Inc.",             exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["NVR",   { name: "NVR Inc.",                      exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["POOL",  { name: "Pool Corporation",               exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["MHK",   { name: "Mohawk Industries Inc.",         exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["WHR",   { name: "Whirlpool Corporation",          exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["NWL",   { name: "Newell Brands Inc.",             exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["HBI",   { name: "Hanesbrands Inc.",               exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["PVH",   { name: "PVH Corp.",                     exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["RL",    { name: "Ralph Lauren Corporation",       exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["TPR",   { name: "Tapestry Inc.",                 exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["CPRI",  { name: "Capri Holdings Limited",         exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["ETSY",  { name: "Etsy Inc.",                     exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["DKNG",  { name: "DraftKings Inc.",               exchange: "NASDAQ", sector: "Consumer", indices: ["SP500"] }],
  ["DECK",  { name: "Deckers Outdoor Corporation",    exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["BWA",   { name: "BorgWarner Inc.",               exchange: "NYSE",   sector: "Consumer", indices: ["SP500"] }],
  ["LULU",  { name: "Lululemon Athletica Inc.",       exchange: "NASDAQ", sector: "Consumer", indices: ["NASDAQ100"] }],
  ["RIVN",  { name: "Rivian Automotive Inc.",         exchange: "NASDAQ", sector: "Consumer", indices: [] }],
  ["LCID",  { name: "Lucid Group Inc.",               exchange: "NASDAQ", sector: "Consumer", indices: [] }],
  ["YUM",   { name: "Yum! Brands Inc.",               exchange: "NYSE",   sector: "Consumer", indices: [] }],
  ["SBUX",  { name: "Starbucks Corporation",          exchange: "NASDAQ", sector: "Consumer", indices: ["SP500","NASDAQ100"] }],
  ["WEN",   { name: "The Wendy's Company",            exchange: "NASDAQ", sector: "Consumer", indices: [] }],
  ["LYFT",  { name: "Lyft Inc.",                     exchange: "NASDAQ", sector: "Consumer", indices: [] }],

  // ── Consumer Staples ──────────────────────────────────────────────────────
  ["WMT",   { name: "Walmart Inc.",                  exchange: "NYSE",   sector: "Staples",  indices: ["SP500","DOW30"] }],
  ["PG",    { name: "Procter & Gamble Company",       exchange: "NYSE",   sector: "Staples",  indices: ["SP500","DOW30"] }],
  ["KO",    { name: "The Coca-Cola Company",          exchange: "NYSE",   sector: "Staples",  indices: ["SP500","DOW30"] }],
  ["PEP",   { name: "PepsiCo Inc.",                  exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],
  ["COST",  { name: "Costco Wholesale Corporation",   exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],
  ["PM",    { name: "Philip Morris International",    exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["MO",    { name: "Altria Group Inc.",              exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["MDLZ",  { name: "Mondelēz International Inc.",    exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],
  ["CL",    { name: "Colgate-Palmolive Company",      exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["GIS",   { name: "General Mills Inc.",             exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["STZ",   { name: "Constellation Brands Inc.",      exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["TSN",   { name: "Tyson Foods Inc.",               exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["CLX",   { name: "The Clorox Company",             exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["MNST",  { name: "Monster Beverage Corporation",   exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],
  ["KDP",   { name: "Keurig Dr Pepper Inc.",          exchange: "NASDAQ", sector: "Staples",  indices: ["SP500"] }],
  ["WBA",   { name: "Walgreens Boots Alliance Inc.",  exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","DOW30"] }],
  ["SYY",   { name: "Sysco Corporation",              exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["HRL",   { name: "Hormel Foods Corporation",       exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["MKC",   { name: "McCormick & Company",            exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["K",     { name: "Kellanova",                      exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["SJM",   { name: "J.M. Smucker Company",          exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["CAG",   { name: "Conagra Brands Inc.",            exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["CPB",   { name: "Campbell Soup Company",          exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["KHC",   { name: "The Kraft Heinz Company",        exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],
  ["CHD",   { name: "Church & Dwight Co. Inc.",       exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["BG",    { name: "Bunge Global SA",               exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["ADM",   { name: "Archer-Daniels-Midland Company", exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["EL",    { name: "The Estée Lauder Companies",     exchange: "NYSE",   sector: "Staples",  indices: ["SP500"] }],
  ["ULTA",  { name: "Ulta Beauty Inc.",               exchange: "NASDAQ", sector: "Staples",  indices: ["SP500","NASDAQ100"] }],

  // ── Energy ────────────────────────────────────────────────────────────────
  ["XOM",   { name: "Exxon Mobil Corporation",        exchange: "NYSE",   sector: "Energy",   indices: ["SP500","DOW30"] }],
  ["CVX",   { name: "Chevron Corporation",            exchange: "NYSE",   sector: "Energy",   indices: ["SP500","DOW30"] }],
  ["COP",   { name: "ConocoPhillips",                 exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["EOG",   { name: "EOG Resources Inc.",             exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["SLB",   { name: "Schlumberger Limited",           exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["OXY",   { name: "Occidental Petroleum Corporation",exchange: "NYSE",  sector: "Energy",   indices: ["SP500"] }],
  ["MPC",   { name: "Marathon Petroleum Corporation", exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["VLO",   { name: "Valero Energy Corporation",      exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["DVN",   { name: "Devon Energy Corporation",       exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["FANG",  { name: "Diamondback Energy Inc.",        exchange: "NASDAQ", sector: "Energy",   indices: ["SP500","NASDAQ100"] }],
  ["HES",   { name: "Hess Corporation",               exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["BKR",   { name: "Baker Hughes Company",           exchange: "NASDAQ", sector: "Energy",   indices: ["SP500"] }],
  ["HAL",   { name: "Halliburton Company",            exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["PSX",   { name: "Phillips 66",                    exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["TRGP",  { name: "Targa Resources Corp.",          exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["OKE",   { name: "ONEOK Inc.",                    exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["KMI",   { name: "Kinder Morgan Inc.",             exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["WMB",   { name: "Williams Companies Inc.",        exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["CTRA",  { name: "Coterra Energy Inc.",            exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["APA",   { name: "APA Corporation",               exchange: "NASDAQ", sector: "Energy",   indices: ["SP500"] }],
  ["MRO",   { name: "Marathon Oil Corporation",       exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["EQT",   { name: "EQT Corporation",               exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],
  ["CHK",   { name: "Chesapeake Energy Corporation",  exchange: "NASDAQ", sector: "Energy",   indices: ["SP500"] }],
  ["ENPH",  { name: "Enphase Energy Inc.",            exchange: "NASDAQ", sector: "Energy",   indices: ["SP500","NASDAQ100"] }],
  ["FSLR",  { name: "First Solar Inc.",               exchange: "NASDAQ", sector: "Energy",   indices: ["SP500","NASDAQ100"] }],
  ["NRG",   { name: "NRG Energy Inc.",               exchange: "NYSE",   sector: "Energy",   indices: ["SP500"] }],

  // ── Financials ────────────────────────────────────────────────────────────
  ["JPM",   { name: "JPMorgan Chase & Co.",           exchange: "NYSE",   sector: "Finance",  indices: ["SP500","DOW30"] }],
  ["BAC",   { name: "Bank of America Corporation",    exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["WFC",   { name: "Wells Fargo & Company",          exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["GS",    { name: "The Goldman Sachs Group Inc.",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500","DOW30"] }],
  ["MS",    { name: "Morgan Stanley",                 exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["C",     { name: "Citigroup Inc.",                 exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["USB",   { name: "U.S. Bancorp",                  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["TFC",   { name: "Truist Financial Corporation",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["PNC",   { name: "PNC Financial Services Group",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["COF",   { name: "Capital One Financial Corporation",exchange: "NYSE",  sector: "Finance",  indices: ["SP500"] }],
  ["AXP",   { name: "American Express Company",       exchange: "NYSE",   sector: "Finance",  indices: ["SP500","DOW30"] }],
  ["BK",    { name: "Bank of New York Mellon Corp.",  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["STT",   { name: "State Street Corporation",       exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["NTRS",  { name: "Northern Trust Corporation",     exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["HBAN",  { name: "Huntington Bancshares Inc.",     exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["RF",    { name: "Regions Financial Corporation",  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["CFG",   { name: "Citizens Financial Group Inc.",  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["MTB",   { name: "M&T Bank Corporation",           exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["ZION",  { name: "Zions Bancorporation",           exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["KEY",   { name: "KeyCorp",                        exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["FITB",  { name: "Fifth Third Bancorp",            exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["CMA",   { name: "Comerica Incorporated",          exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["SYF",   { name: "Synchrony Financial",            exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["DFS",   { name: "Discover Financial Services",    exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["AIG",   { name: "American International Group",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["MET",   { name: "MetLife Inc.",                   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["PRU",   { name: "Prudential Financial Inc.",      exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["AFL",   { name: "Aflac Incorporated",             exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["ALL",   { name: "The Allstate Corporation",       exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["TRV",   { name: "The Travelers Companies Inc.",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500","DOW30"] }],
  ["HIG",   { name: "Hartford Financial Services",    exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["CB",    { name: "Chubb Limited",                 exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["LNC",   { name: "Lincoln National Corporation",   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["UNM",   { name: "Unum Group",                    exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["GL",    { name: "Globe Life Inc.",               exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["AIZ",   { name: "Assurant Inc.",                 exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["EQH",   { name: "Equitable Holdings Inc.",        exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["PFG",   { name: "Principal Financial Group Inc.", exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["BLK",   { name: "BlackRock Inc.",                exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["SCHW",  { name: "Charles Schwab Corporation",     exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["CME",   { name: "CME Group Inc.",                exchange: "NASDAQ", sector: "Finance",  indices: ["SP500","NASDAQ100"] }],
  ["ICE",   { name: "Intercontinental Exchange Inc.", exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["SPGI",  { name: "S&P Global Inc.",               exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["MCO",   { name: "Moody's Corporation",            exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["V",     { name: "Visa Inc.",                     exchange: "NYSE",   sector: "Finance",  indices: ["SP500","DOW30"] }],
  ["MA",    { name: "Mastercard Incorporated",        exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["FI",    { name: "Fiserv Inc.",                   exchange: "NASDAQ", sector: "Finance",  indices: ["SP500","NASDAQ100"] }],
  ["GPN",   { name: "Global Payments Inc.",           exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["CPAY",  { name: "Corpay Inc.",                   exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["WEX",   { name: "WEX Inc.",                      exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["BR",    { name: "Broadridge Financial Solutions", exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["AMP",   { name: "Ameriprise Financial Inc.",      exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["BEN",   { name: "Franklin Resources Inc.",        exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["IVZ",   { name: "Invesco Ltd.",                  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["TROW",  { name: "T. Rowe Price Group Inc.",       exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["AMG",   { name: "Affiliated Managers Group Inc.", exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["CBOE",  { name: "Cboe Global Markets Inc.",       exchange: "CBOE",   sector: "Finance",  indices: ["SP500"] }],
  ["KKR",   { name: "KKR & Co. Inc.",                exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["APO",   { name: "Apollo Global Management Inc.",  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["BX",    { name: "Blackstone Inc.",               exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["MMC",   { name: "Marsh & McLennan Companies",     exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["AJG",   { name: "Arthur J. Gallagher & Co.",      exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["WTW",   { name: "Willis Towers Watson PLC",       exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["AON",   { name: "Aon PLC",                       exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["ALLY",  { name: "Ally Financial Inc.",            exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["ACGL",  { name: "Arch Capital Group Ltd.",        exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["CINF",  { name: "Cincinnati Financial Corporation",exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["ERIE",  { name: "Erie Indemnity Company",         exchange: "NASDAQ", sector: "Finance",  indices: ["SP500"] }],
  ["FNF",   { name: "Fidelity National Financial Inc.",exchange: "NYSE",  sector: "Finance",  indices: ["SP500"] }],
  ["AFG",   { name: "American Financial Group Inc.",  exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["FAF",   { name: "First American Financial Corp.", exchange: "NYSE",   sector: "Finance",  indices: ["SP500"] }],
  ["COIN",  { name: "Coinbase Global Inc.",           exchange: "NASDAQ", sector: "Finance",  indices: [] }],
  ["HOOD",  { name: "Robinhood Markets Inc.",         exchange: "NASDAQ", sector: "Finance",  indices: [] }],
  ["SOFI",  { name: "SoFi Technologies Inc.",         exchange: "NASDAQ", sector: "Finance",  indices: [] }],
  ["AFRM",  { name: "Affirm Holdings Inc.",           exchange: "NASDAQ", sector: "Finance",  indices: [] }],
  ["MSTR",  { name: "MicroStrategy Incorporated",     exchange: "NASDAQ", sector: "Finance",  indices: [] }],
  ["PYPL",  { name: "PayPal Holdings Inc.",           exchange: "NASDAQ", sector: "Finance",  indices: ["SP500","NASDAQ100"] }],

  // ── Health Care ───────────────────────────────────────────────────────────
  ["UNH",   { name: "UnitedHealth Group Inc.",        exchange: "NYSE",   sector: "Health",   indices: ["SP500","DOW30"] }],
  ["JNJ",   { name: "Johnson & Johnson",              exchange: "NYSE",   sector: "Health",   indices: ["SP500","DOW30"] }],
  ["LLY",   { name: "Eli Lilly and Company",          exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["ABT",   { name: "Abbott Laboratories",            exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["MRK",   { name: "Merck & Co. Inc.",               exchange: "NYSE",   sector: "Health",   indices: ["SP500","DOW30"] }],
  ["PFE",   { name: "Pfizer Inc.",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500","DOW30"] }],
  ["ABBV",  { name: "AbbVie Inc.",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["TMO",   { name: "Thermo Fisher Scientific Inc.",  exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["BMY",   { name: "Bristol-Myers Squibb Company",   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["AMGN",  { name: "Amgen Inc.",                    exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100","DOW30"] }],
  ["GILD",  { name: "Gilead Sciences Inc.",           exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["BIIB",  { name: "Biogen Inc.",                   exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["REGN",  { name: "Regeneron Pharmaceuticals",      exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["VRTX",  { name: "Vertex Pharmaceuticals Inc.",    exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["ISRG",  { name: "Intuitive Surgical Inc.",        exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["MDT",   { name: "Medtronic PLC",                 exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["BSX",   { name: "Boston Scientific Corporation",  exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["ZTS",   { name: "Zoetis Inc.",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["EW",    { name: "Edwards Lifesciences Corporation",exchange: "NYSE",  sector: "Health",   indices: ["SP500"] }],
  ["DHR",   { name: "Danaher Corporation",            exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["STE",   { name: "STERIS PLC",                    exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["IQV",   { name: "IQVIA Holdings Inc.",            exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["DXCM",  { name: "Dexcom Inc.",                   exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["MRNA",  { name: "Moderna Inc.",                  exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["IDXX",  { name: "IDEXX Laboratories Inc.",        exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["ALGN",  { name: "Align Technology Inc.",          exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["GEHC",  { name: "GE HealthCare Technologies Inc.",exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["HCA",   { name: "HCA Healthcare Inc.",            exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["CI",    { name: "Cigna Group",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["ELV",   { name: "Elevance Health Inc.",           exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["MOH",   { name: "Molina Healthcare Inc.",         exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["HUM",   { name: "Humana Inc.",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["CVS",   { name: "CVS Health Corporation",         exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["MCK",   { name: "McKesson Corporation",           exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["ABC",   { name: "AmerisourceBergen Corporation",  exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["CAH",   { name: "Cardinal Health Inc.",           exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["DGX",   { name: "Quest Diagnostics Incorporated", exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["LH",    { name: "Laboratory Corporation of America",exchange: "NYSE", sector: "Health",   indices: ["SP500"] }],
  ["RMD",   { name: "ResMed Inc.",                   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["HOLX",  { name: "Hologic Inc.",                  exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["PODD",  { name: "Insulet Corporation",            exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["MASI",  { name: "Masimo Corporation",             exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["HSIC",  { name: "Henry Schein Inc.",              exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["ZBH",   { name: "Zimmer Biomet Holdings Inc.",    exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["RVTY",  { name: "Revvity Inc.",                  exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["MTD",   { name: "Mettler-Toledo International",   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["WAT",   { name: "Waters Corporation",             exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["A",     { name: "Agilent Technologies Inc.",      exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["BAX",   { name: "Baxter International Inc.",      exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["BDX",   { name: "Becton Dickinson and Company",   exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["BIO",   { name: "Bio-Rad Laboratories Inc.",      exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["NTRA",  { name: "Natera Inc.",                   exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["VTRS",  { name: "Viatris Inc.",                  exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["INCY",  { name: "Incyte Corporation",             exchange: "NASDAQ", sector: "Health",   indices: ["SP500","NASDAQ100"] }],
  ["JAZZ",  { name: "Jazz Pharmaceuticals PLC",       exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["EXAS",  { name: "Exact Sciences Corporation",     exchange: "NASDAQ", sector: "Health",   indices: ["SP500"] }],
  ["SOLV",  { name: "Solventum Corporation",          exchange: "NYSE",   sector: "Health",   indices: ["SP500"] }],
  ["HIMS",  { name: "Hims & Hers Health Inc.",        exchange: "NYSE",   sector: "Health",   indices: [] }],
  ["ILMN",  { name: "Illumina Inc.",                 exchange: "NASDAQ", sector: "Health",   indices: ["NASDAQ100"] }],

  // ── Industrials ───────────────────────────────────────────────────────────
  ["GE",    { name: "GE Aerospace",                  exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["HON",   { name: "Honeywell International Inc.",   exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","DOW30"] }],
  ["CAT",   { name: "Caterpillar Inc.",               exchange: "NYSE",   sector: "Indust",   indices: ["SP500","DOW30"] }],
  ["DE",    { name: "Deere & Company",                exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["UPS",   { name: "United Parcel Service Inc.",     exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["FDX",   { name: "FedEx Corporation",              exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["RTX",   { name: "RTX Corporation",               exchange: "NYSE",   sector: "Indust",   indices: ["SP500","DOW30"] }],
  ["LMT",   { name: "Lockheed Martin Corporation",    exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["NOC",   { name: "Northrop Grumman Corporation",   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["GD",    { name: "General Dynamics Corporation",   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["BA",    { name: "The Boeing Company",             exchange: "NYSE",   sector: "Indust",   indices: ["SP500","DOW30"] }],
  ["MMM",   { name: "3M Company",                    exchange: "NYSE",   sector: "Indust",   indices: ["SP500","DOW30"] }],
  ["ETN",   { name: "Eaton Corporation PLC",          exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["EMR",   { name: "Emerson Electric Co.",           exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["AME",   { name: "AMETEK Inc.",                   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["ROK",   { name: "Rockwell Automation Inc.",       exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["PH",    { name: "Parker-Hannifin Corporation",    exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["ITW",   { name: "Illinois Tool Works Inc.",       exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["GWW",   { name: "W.W. Grainger Inc.",             exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["PCAR",  { name: "PACCAR Inc.",                   exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["OTIS",  { name: "Otis Worldwide Corporation",     exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["CTAS",  { name: "Cintas Corporation",             exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["CSX",   { name: "CSX Corporation",               exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["UNP",   { name: "Union Pacific Corporation",      exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["NSC",   { name: "Norfolk Southern Corporation",   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["FAST",  { name: "Fastenal Company",               exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["ODFL",  { name: "Old Dominion Freight Line Inc.", exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["URI",   { name: "United Rentals Inc.",            exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["WCN",   { name: "Waste Connections Inc.",         exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["WM",    { name: "Waste Management Inc.",          exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["LHX",   { name: "L3Harris Technologies Inc.",     exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["HUBB",  { name: "Hubbell Incorporated",           exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["SWK",   { name: "Stanley Black & Decker Inc.",    exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["TT",    { name: "Trane Technologies PLC",         exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["CPRT",  { name: "Copart Inc.",                   exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["TDG",   { name: "TransDigm Group Incorporated",   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["TDY",   { name: "Teledyne Technologies Inc.",     exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["HII",   { name: "Huntington Ingalls Industries",  exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["AXON",  { name: "Axon Enterprise Inc.",           exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["LDOS",  { name: "Leidos Holdings Inc.",           exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["SAIC",  { name: "Science Applications International",exchange: "NYSE", sector: "Indust",  indices: ["SP500"] }],
  ["BAH",   { name: "Booz Allen Hamilton Holding Corp",exchange: "NYSE",  sector: "Indust",   indices: ["SP500"] }],
  ["PNR",   { name: "Pentair PLC",                   exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["GNRC",  { name: "Generac Holdings Inc.",          exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["ALLE",  { name: "Allegion PLC",                  exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["MAS",   { name: "Masco Corporation",              exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["DOV",   { name: "Dover Corporation",              exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["IEX",   { name: "IDEX Corporation",               exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["EXPD",  { name: "Expeditors International",       exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["XPO",   { name: "XPO Inc.",                      exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["CHRW",  { name: "C.H. Robinson Worldwide Inc.",   exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["JBHT",  { name: "J.B. Hunt Transport Services",   exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["WAB",   { name: "Wabtec Corporation",             exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["CARR",  { name: "Carrier Global Corporation",     exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["TRMB",  { name: "Trimble Inc.",                  exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["FTV",   { name: "Fortive Corporation",            exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["NDSN",  { name: "Nordson Corporation",            exchange: "NASDAQ", sector: "Indust",   indices: ["SP500"] }],
  ["CGNX",  { name: "Cognex Corporation",             exchange: "NASDAQ", sector: "Indust",   indices: ["SP500"] }],
  ["RBC",   { name: "RBC Bearings Incorporated",      exchange: "NASDAQ", sector: "Indust",   indices: ["SP500"] }],
  ["HWM",   { name: "Howmet Aerospace Inc.",          exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["EFX",   { name: "Equifax Inc.",                  exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["VRSK",  { name: "Verisk Analytics Inc.",          exchange: "NASDAQ", sector: "Indust",   indices: ["SP500","NASDAQ100"] }],
  ["RSG",   { name: "Republic Services Inc.",         exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["GEV",   { name: "GE Vernova LLC",                exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["UBER",  { name: "Uber Technologies Inc.",         exchange: "NYSE",   sector: "Indust",   indices: ["SP500"] }],
  ["DASH",  { name: "DoorDash Inc.",                 exchange: "NASDAQ", sector: "Indust",   indices: ["SP500"] }],
  ["RKLB",  { name: "Rocket Lab USA Inc.",            exchange: "NASDAQ", sector: "Indust",   indices: [] }],
  ["JOBY",  { name: "Joby Aviation Inc.",             exchange: "NYSE",   sector: "Indust",   indices: [] }],
  ["SPCE",  { name: "Virgin Galactic Holdings Inc.",  exchange: "NYSE",   sector: "Indust",   indices: [] }],

  // ── Information Technology ────────────────────────────────────────────────
  ["AAPL",  { name: "Apple Inc.",                    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100","DOW30"] }],
  ["MSFT",  { name: "Microsoft Corporation",          exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100","DOW30"] }],
  ["NVDA",  { name: "NVIDIA Corporation",             exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["AVGO",  { name: "Broadcom Inc.",                 exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["AMD",   { name: "Advanced Micro Devices Inc.",    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["QCOM",  { name: "Qualcomm Incorporated",          exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["TXN",   { name: "Texas Instruments Incorporated", exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["MU",    { name: "Micron Technology Inc.",         exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["LRCX",  { name: "Lam Research Corporation",       exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["AMAT",  { name: "Applied Materials Inc.",         exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["KLAC",  { name: "KLA Corporation",               exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["MCHP",  { name: "Microchip Technology Inc.",      exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ADI",   { name: "Analog Devices Inc.",            exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ON",    { name: "ON Semiconductor Corporation",   exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["NXPI",  { name: "NXP Semiconductors N.V.",       exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["SWKS",  { name: "Skyworks Solutions Inc.",        exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["MPWR",  { name: "Monolithic Power Systems Inc.",  exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ACN",   { name: "Accenture PLC",                 exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["IBM",   { name: "International Business Machines",exchange: "NYSE",   sector: "Tech",     indices: ["SP500","DOW30"] }],
  ["ORCL",  { name: "Oracle Corporation",             exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["CSCO",  { name: "Cisco Systems Inc.",             exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100","DOW30"] }],
  ["HPQ",   { name: "HP Inc.",                       exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["HPE",   { name: "Hewlett Packard Enterprise",     exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["NTAP",  { name: "NetApp Inc.",                   exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["CDW",   { name: "CDW Corporation",               exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["FFIV",  { name: "F5 Inc.",                       exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["AKAM",  { name: "Akamai Technologies Inc.",       exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["JNPR",  { name: "Juniper Networks Inc.",          exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["CRM",   { name: "Salesforce Inc.",               exchange: "NYSE",   sector: "Tech",     indices: ["SP500","DOW30"] }],
  ["ADBE",  { name: "Adobe Inc.",                    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["INTU",  { name: "Intuit Inc.",                   exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["NOW",   { name: "ServiceNow Inc.",               exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["FTNT",  { name: "Fortinet Inc.",                 exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["PANW",  { name: "Palo Alto Networks Inc.",        exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["CRWD",  { name: "CrowdStrike Holdings Inc.",      exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ANSS",  { name: "ANSYS Inc.",                    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["CDNS",  { name: "Cadence Design Systems Inc.",    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["SNPS",  { name: "Synopsys Inc.",                 exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["EPAM",  { name: "EPAM Systems Inc.",              exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["CTSH",  { name: "Cognizant Technology Solutions", exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["IT",    { name: "Gartner Inc.",                  exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["GFS",   { name: "GlobalFoundries Inc.",           exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["PTC",   { name: "PTC Inc.",                      exchange: "NASDAQ", sector: "Tech",     indices: ["SP500"] }],
  ["ROP",   { name: "Roper Technologies Inc.",        exchange: "NASDAQ", sector: "Tech",     indices: ["SP500"] }],
  ["KEYS",  { name: "Keysight Technologies Inc.",     exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["PAYX",  { name: "Paychex Inc.",                  exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ADP",   { name: "Automatic Data Processing Inc.", exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["FIS",   { name: "Fidelity National Information",  exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["FISV",  { name: "Fiserv Inc.",                   exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["JKHY",  { name: "Jack Henry & Associates Inc.",   exchange: "NASDAQ", sector: "Tech",     indices: ["SP500"] }],
  ["PAYC",  { name: "Paycom Software Inc.",           exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["PCTY",  { name: "Paylocity Holding Corporation",  exchange: "NASDAQ", sector: "Tech",     indices: ["SP500"] }],
  ["GLW",   { name: "Corning Incorporated",           exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["TYL",   { name: "Tyler Technologies Inc.",        exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["VRT",   { name: "Vertiv Holdings Co.",            exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["ZBRA",  { name: "Zebra Technologies Corporation", exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["APH",   { name: "Amphenol Corporation",           exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["TE",    { name: "TE Connectivity Ltd.",           exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["WDC",   { name: "Western Digital Corporation",    exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["STX",   { name: "Seagate Technology Holdings PLC",exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["GEN",   { name: "Gen Digital Inc.",               exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["DELL",  { name: "Dell Technologies Inc.",         exchange: "NYSE",   sector: "Tech",     indices: ["SP500"] }],
  ["ANET",  { name: "Arista Networks Inc.",           exchange: "NYSE",   sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["ADSK",  { name: "Autodesk Inc.",                 exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["CSGP",  { name: "CoStar Group Inc.",              exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["CHKP",  { name: "Check Point Software Technologies",exchange: "NASDAQ",sector: "Tech",    indices: ["NASDAQ100"] }],
  ["PLTR",  { name: "Palantir Technologies Inc.",     exchange: "NYSE",   sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["APP",   { name: "AppLovin Corporation",           exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["SMCI",  { name: "Super Micro Computer Inc.",      exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["NET",   { name: "Cloudflare Inc.",               exchange: "NYSE",   sector: "Tech",     indices: [] }],
  ["SNOW",  { name: "Snowflake Inc.",                exchange: "NYSE",   sector: "Tech",     indices: [] }],
  ["MDB",   { name: "MongoDB Inc.",                  exchange: "NASDAQ", sector: "Tech",     indices: [] }],
  ["ZS",    { name: "Zscaler Inc.",                  exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100"] }],
  ["DDOG",  { name: "Datadog Inc.",                  exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100"] }],
  ["WDAY",  { name: "Workday Inc.",                  exchange: "NASDAQ", sector: "Tech",     indices: ["SP500","NASDAQ100"] }],
  ["TEAM",  { name: "Atlassian Corporation PLC",      exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100"] }],
  ["TTD",   { name: "The Trade Desk Inc.",            exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100"] }],
  ["OKTA",  { name: "Okta Inc.",                     exchange: "NASDAQ", sector: "Tech",     indices: [] }],
  ["ZM",    { name: "Zoom Video Communications",      exchange: "NASDAQ", sector: "Tech",     indices: [] }],
  ["DOCU",  { name: "DocuSign Inc.",                 exchange: "NASDAQ", sector: "Tech",     indices: [] }],
  ["IONQ",  { name: "IonQ Inc.",                     exchange: "NYSE",   sector: "Tech",     indices: [] }],
  ["RGTI",  { name: "Rigetti Computing Inc.",         exchange: "NASDAQ", sector: "Tech",     indices: [] }],
  ["QBTS",  { name: "D-Wave Quantum Inc.",            exchange: "NYSE",   sector: "Tech",     indices: [] }],
  ["MRVL",  { name: "Marvell Technology Inc.",        exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100"] }],

  // ── Materials ─────────────────────────────────────────────────────────────
  ["LIN",   { name: "Linde PLC",                     exchange: "NASDAQ", sector: "Matls",    indices: ["SP500"] }],
  ["APD",   { name: "Air Products and Chemicals Inc.",exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["ECL",   { name: "Ecolab Inc.",                   exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["SHW",   { name: "The Sherwin-Williams Company",   exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["NUE",   { name: "Nucor Corporation",              exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["FCX",   { name: "Freeport-McMoRan Inc.",          exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["VMC",   { name: "Vulcan Materials Company",       exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["CF",    { name: "CF Industries Holdings Inc.",    exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["PKG",   { name: "Packaging Corporation of America",exchange: "NYSE",  sector: "Matls",    indices: ["SP500"] }],
  ["FMC",   { name: "FMC Corporation",               exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["PPG",   { name: "PPG Industries Inc.",            exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["IFF",   { name: "International Flavors & Fragrances",exchange: "NYSE", sector: "Matls",   indices: ["SP500"] }],
  ["EMN",   { name: "Eastman Chemical Company",       exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["CE",    { name: "Celanese Corporation",           exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["LYB",   { name: "LyondellBasell Industries N.V.", exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["DD",    { name: "DuPont de Nemours Inc.",         exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["DOW",   { name: "Dow Inc.",                      exchange: "NYSE",   sector: "Matls",    indices: ["SP500","DOW30"] }],
  ["RPM",   { name: "RPM International Inc.",         exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["ALB",   { name: "Albemarle Corporation",          exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["WRK",   { name: "WestRock Company",               exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["IP",    { name: "International Paper Company",    exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["SEE",   { name: "Sealed Air Corporation",         exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["ATI",   { name: "ATI Inc.",                      exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["RS",    { name: "Reliance Inc.",                 exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],
  ["STLD",  { name: "Steel Dynamics Inc.",            exchange: "NASDAQ", sector: "Matls",    indices: ["SP500"] }],
  ["CLF",   { name: "Cleveland-Cliffs Inc.",          exchange: "NYSE",   sector: "Matls",    indices: ["SP500"] }],

  // ── Real Estate ───────────────────────────────────────────────────────────
  ["PLD",   { name: "Prologis Inc.",                 exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["AMT",   { name: "American Tower Corporation",     exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["EQIX",  { name: "Equinix Inc.",                  exchange: "NASDAQ", sector: "RealEst",  indices: ["SP500"] }],
  ["CCI",   { name: "Crown Castle Inc.",              exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["SPG",   { name: "Simon Property Group Inc.",      exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["DLR",   { name: "Digital Realty Trust Inc.",      exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["PSA",   { name: "Public Storage",                 exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["WELL",  { name: "Welltower Inc.",                exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["CBRE",  { name: "CBRE Group Inc.",               exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["ARE",   { name: "Alexandria Real Estate Equities",exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["AVB",   { name: "AvalonBay Communities Inc.",     exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["EQR",   { name: "Equity Residential",             exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["ESS",   { name: "Essex Property Trust Inc.",      exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["MAA",   { name: "Mid-America Apartment Communities",exchange: "NYSE", sector: "RealEst",  indices: ["SP500"] }],
  ["UDR",   { name: "UDR Inc.",                      exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["CPT",   { name: "Camden Property Trust",          exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["BXP",   { name: "Boston Properties Inc.",         exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["VNO",   { name: "Vornado Realty Trust",           exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["KIM",   { name: "Kimco Realty Corporation",       exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["REG",   { name: "Regency Centers Corporation",    exchange: "NASDAQ", sector: "RealEst",  indices: ["SP500"] }],
  ["FRT",   { name: "Federal Realty Investment Trust",exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["NNN",   { name: "NNN REIT Inc.",                 exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["O",     { name: "Realty Income Corporation",      exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["WY",    { name: "Weyerhaeuser Company",           exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["IRM",   { name: "Iron Mountain Incorporated",     exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["SBA",   { name: "SBA Communications Corporation", exchange: "NASDAQ", sector: "RealEst",  indices: ["SP500"] }],
  ["VICI",  { name: "VICI Properties Inc.",           exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["MPW",   { name: "Medical Properties Trust Inc.",  exchange: "NYSE",   sector: "RealEst",  indices: ["SP500"] }],
  ["IIPR",  { name: "Innovative Industrial Properties",exchange: "NYSE",  sector: "RealEst",  indices: ["SP500"] }],

  // ── Utilities ─────────────────────────────────────────────────────────────
  ["NEE",   { name: "NextEra Energy Inc.",            exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["SO",    { name: "The Southern Company",           exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["DUK",   { name: "Duke Energy Corporation",        exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["AEP",   { name: "American Electric Power Company",exchange: "NASDAQ", sector: "Utility",  indices: ["SP500"] }],
  ["SRE",   { name: "Sempra Energy",                 exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["D",     { name: "Dominion Energy Inc.",           exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["EXC",   { name: "Exelon Corporation",             exchange: "NASDAQ", sector: "Utility",  indices: ["SP500","NASDAQ100"] }],
  ["PCG",   { name: "PG&E Corporation",               exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["ES",    { name: "Eversource Energy",              exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["EIX",   { name: "Edison International",           exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["ATO",   { name: "Atmos Energy Corporation",       exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["CEG",   { name: "Constellation Energy Corporation",exchange: "NASDAQ",sector: "Utility",  indices: ["SP500","NASDAQ100"] }],
  ["WEC",   { name: "WEC Energy Group Inc.",          exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["CNP",   { name: "CenterPoint Energy Inc.",        exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["LNT",   { name: "Alliant Energy Corporation",     exchange: "NASDAQ", sector: "Utility",  indices: ["SP500"] }],
  ["EVRG",  { name: "Evergy Inc.",                   exchange: "NASDAQ", sector: "Utility",  indices: ["SP500"] }],
  ["NI",    { name: "NiSource Inc.",                 exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["AEE",   { name: "Ameren Corporation",             exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["DTE",   { name: "DTE Energy Company",             exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["PPL",   { name: "PPL Corporation",               exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["CMS",   { name: "CMS Energy Corporation",         exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["NRG",   { name: "NRG Energy Inc.",               exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["AWK",   { name: "American Water Works Company",   exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["XEL",   { name: "Xcel Energy Inc.",               exchange: "NASDAQ", sector: "Utility",  indices: ["SP500"] }],
  ["PNW",   { name: "Pinnacle West Capital Corporation",exchange: "NASDAQ",sector: "Utility", indices: ["SP500"] }],
  ["AES",   { name: "The AES Corporation",            exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],
  ["VST",   { name: "Vistra Corp.",                  exchange: "NYSE",   sector: "Utility",  indices: ["SP500"] }],

  // ── ETFs — Broad Market ───────────────────────────────────────────────────
  ["SPY",   { name: "SPDR S&P 500 ETF Trust",         exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VOO",   { name: "Vanguard S&P 500 ETF",           exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["IVV",   { name: "iShares Core S&P 500 ETF",       exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VTI",   { name: "Vanguard Total Stock Market ETF",exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["QQQ",   { name: "Invesco QQQ Trust",              exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["QQQM",  { name: "Invesco Nasdaq 100 ETF",         exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["DIA",   { name: "SPDR Dow Jones Industrial Average ETF",exchange: "NYSE",sector: "ETF",   indices: ["ETF"] }],
  ["IWM",   { name: "iShares Russell 2000 ETF",       exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VUG",   { name: "Vanguard Growth ETF",            exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VTV",   { name: "Vanguard Value ETF",             exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["SCHB",  { name: "Schwab U.S. Broad Market ETF",   exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["ITOT",  { name: "iShares Core S&P Total US Mkt",  exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VIG",   { name: "Vanguard Dividend Appreciation ETF",exchange: "NYSE", sector: "ETF",     indices: ["ETF"] }],
  ["SCHD",  { name: "Schwab U.S. Dividend Equity ETF",exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["DVY",   { name: "iShares Select Dividend ETF",    exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],

  // ── ETFs — Sector SPDR ────────────────────────────────────────────────────
  ["XLK",   { name: "Technology Select Sector SPDR ETF",exchange: "NYSE", sector: "ETF",      indices: ["ETF"] }],
  ["XLF",   { name: "Financial Select Sector SPDR ETF",exchange: "NYSE",  sector: "ETF",      indices: ["ETF"] }],
  ["XLV",   { name: "Health Care Select Sector SPDR ETF",exchange: "NYSE", sector: "ETF",     indices: ["ETF"] }],
  ["XLE",   { name: "Energy Select Sector SPDR ETF",  exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["XLI",   { name: "Industrial Select Sector SPDR ETF",exchange: "NYSE", sector: "ETF",      indices: ["ETF"] }],
  ["XLY",   { name: "Consumer Discretionary Select SPDR",exchange: "NYSE",sector: "ETF",      indices: ["ETF"] }],
  ["XLP",   { name: "Consumer Staples Select Sector SPDR",exchange: "NYSE",sector: "ETF",     indices: ["ETF"] }],
  ["XLU",   { name: "Utilities Select Sector SPDR ETF",exchange: "NYSE",  sector: "ETF",      indices: ["ETF"] }],
  ["XLB",   { name: "Materials Select Sector SPDR ETF",exchange: "NYSE",  sector: "ETF",      indices: ["ETF"] }],
  ["XLRE",  { name: "Real Estate Select Sector SPDR ETF",exchange: "NYSE",sector: "ETF",      indices: ["ETF"] }],
  ["XLC",   { name: "Communication Services SPDR ETF",exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],

  // ── ETFs — ARK ────────────────────────────────────────────────────────────
  ["ARKK",  { name: "ARK Innovation ETF",             exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["ARKQ",  { name: "ARK Autonomous Technology & Robotics ETF",exchange: "NYSE",sector: "ETF", indices: ["ETF"] }],
  ["ARKG",  { name: "ARK Genomic Revolution ETF",     exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["ARKW",  { name: "ARK Next Generation Internet ETF",exchange: "NYSE",  sector: "ETF",      indices: ["ETF"] }],
  ["ARKF",  { name: "ARK Fintech Innovation ETF",     exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["ARKX",  { name: "ARK Space Exploration & Innovation ETF",exchange: "NYSE",sector: "ETF",  indices: ["ETF"] }],

  // ── ETFs — Fixed Income / Multi-Asset ────────────────────────────────────
  ["TLT",   { name: "iShares 20+ Year Treasury Bond ETF",exchange: "NASDAQ",sector: "ETF",   indices: ["ETF"] }],
  ["IEF",   { name: "iShares 7-10 Year Treasury Bond ETF",exchange: "NASDAQ",sector: "ETF",  indices: ["ETF"] }],
  ["SHY",   { name: "iShares 1-3 Year Treasury Bond ETF",exchange: "NASDAQ",sector: "ETF",   indices: ["ETF"] }],
  ["BND",   { name: "Vanguard Total Bond Market ETF", exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["AGG",   { name: "iShares Core US Aggregate Bond ETF",exchange: "NYSE", sector: "ETF",     indices: ["ETF"] }],
  ["HYG",   { name: "iShares iBoxx $ High Yield Corp Bond ETF",exchange: "NYSE",sector: "ETF",indices: ["ETF"] }],
  ["LQD",   { name: "iShares iBoxx $ Inv Grade Corp Bond ETF",exchange: "NYSE",sector: "ETF", indices: ["ETF"] }],

  // ── ETFs — Commodities ────────────────────────────────────────────────────
  ["GLD",   { name: "SPDR Gold Shares",               exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["IAU",   { name: "iShares Gold Trust",             exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["SLV",   { name: "iShares Silver Trust",           exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["GDX",   { name: "VanEck Gold Miners ETF",         exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["GDXJ",  { name: "VanEck Junior Gold Miners ETF",  exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["USO",   { name: "United States Oil Fund LP",      exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["UNG",   { name: "United States Natural Gas Fund", exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["PDBC",  { name: "Invesco Optimum Yield Diversified Commodity",exchange: "NASDAQ",sector: "ETF",indices: ["ETF"] }],

  // ── ETFs — Crypto / Leveraged / Volatility ───────────────────────────────
  ["IBIT",  { name: "iShares Bitcoin Trust ETF",      exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["FBTC",  { name: "Fidelity Wise Origin Bitcoin ETF",exchange: "NYSE",  sector: "ETF",      indices: ["ETF"] }],
  ["BITO",  { name: "ProShares Bitcoin ETF",          exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["SQQQ",  { name: "ProShares UltraPro Short QQQ",   exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["TQQQ",  { name: "ProShares UltraPro QQQ",         exchange: "NASDAQ", sector: "ETF",      indices: ["ETF"] }],
  ["SPXS",  { name: "Direxion Daily S&P 500 Bear 3X", exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["SPXL",  { name: "Direxion Daily S&P 500 Bull 3X", exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["UVXY",  { name: "ProShares Ultra VIX Short-Term Futures",exchange: "NASDAQ",sector: "ETF", indices: ["ETF"] }],
  ["VXX",   { name: "iPath Series B S&P 500 VIX ETN", exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["VIXY",  { name: "ProShares VIX Short-Term Futures ETF",exchange: "NYSE",sector: "ETF",    indices: ["ETF"] }],

  // ── ETFs — International ──────────────────────────────────────────────────
  ["VEA",   { name: "Vanguard FTSE Developed Markets ETF",exchange: "NYSE",sector: "ETF",     indices: ["ETF"] }],
  ["VWO",   { name: "Vanguard FTSE Emerging Markets ETF",exchange: "NYSE", sector: "ETF",     indices: ["ETF"] }],
  ["EFA",   { name: "iShares MSCI EAFE ETF",          exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["EEM",   { name: "iShares MSCI Emerging Markets ETF",exchange: "NYSE", sector: "ETF",      indices: ["ETF"] }],
  ["FXI",   { name: "iShares China Large-Cap ETF",    exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["EWJ",   { name: "iShares MSCI Japan ETF",         exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["EWZ",   { name: "iShares MSCI Brazil ETF",        exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["INDA",  { name: "iShares MSCI India ETF",         exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["EWT",   { name: "iShares MSCI Taiwan ETF",        exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["EWY",   { name: "iShares MSCI South Korea ETF",   exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],
  ["KWEB",  { name: "KraneShares CSI China Internet ETF",exchange: "NYSE",sector: "ETF",      indices: ["ETF"] }],
  ["CQQQ",  { name: "Invesco China Technology ETF",   exchange: "NYSE",   sector: "ETF",      indices: ["ETF"] }],

  // ── ADRs / Global Names on US Exchanges ───────────────────────────────────
  ["TSM",   { name: "Taiwan Semiconductor Manufacturing",exchange: "NYSE", sector: "Tech",    indices: ["ADR"] }],
  ["ASML",  { name: "ASML Holding N.V.",              exchange: "NASDAQ", sector: "Tech",     indices: ["NASDAQ100","ADR"] }],
  ["SAP",   { name: "SAP SE",                        exchange: "NYSE",   sector: "Tech",     indices: ["ADR"] }],
  ["BABA",  { name: "Alibaba Group Holding Ltd.",     exchange: "NYSE",   sector: "Consumer", indices: ["ADR"] }],
  ["JD",    { name: "JD.com Inc.",                   exchange: "NASDAQ", sector: "Consumer", indices: ["NASDAQ100","ADR"] }],
  ["PDD",   { name: "PDD Holdings Inc. (Temu)",       exchange: "NASDAQ", sector: "Consumer", indices: ["NASDAQ100","ADR"] }],
  ["BIDU",  { name: "Baidu Inc.",                    exchange: "NASDAQ", sector: "Comm",     indices: ["NASDAQ100","ADR"] }],
  ["NTES",  { name: "NetEase Inc.",                  exchange: "NASDAQ", sector: "Comm",     indices: ["NASDAQ100","ADR"] }],
  ["MELI",  { name: "MercadoLibre Inc.",              exchange: "NASDAQ", sector: "Consumer", indices: ["NASDAQ100","ADR"] }],
  ["NVO",   { name: "Novo Nordisk A/S",               exchange: "NYSE",   sector: "Health",   indices: ["ADR"] }],
  ["AZN",   { name: "AstraZeneca PLC",               exchange: "NASDAQ", sector: "Health",   indices: ["NASDAQ100","ADR"] }],
  ["NVS",   { name: "Novartis AG",                   exchange: "NYSE",   sector: "Health",   indices: ["ADR"] }],
  ["RHHBY", { name: "Roche Holding AG",               exchange: "OTC",    sector: "Health",   indices: ["ADR"] }],
  ["SNY",   { name: "Sanofi S.A.",                   exchange: "NASDAQ", sector: "Health",   indices: ["ADR"] }],
  ["TM",    { name: "Toyota Motor Corporation",       exchange: "NYSE",   sector: "Consumer", indices: ["ADR"] }],
  ["SONY",  { name: "Sony Group Corporation",         exchange: "NYSE",   sector: "Consumer", indices: ["ADR"] }],
  ["HMC",   { name: "Honda Motor Co. Ltd.",           exchange: "NYSE",   sector: "Consumer", indices: ["ADR"] }],
  ["NSANY", { name: "Nissan Motor Co. Ltd.",          exchange: "OTC",    sector: "Consumer", indices: ["ADR"] }],
  ["TOYOTA",{ name: "Toyota Motor ADR",               exchange: "NYSE",   sector: "Consumer", indices: ["ADR"] }],
  ["BP",    { name: "BP PLC",                        exchange: "NYSE",   sector: "Energy",   indices: ["ADR"] }],
  ["SHEL",  { name: "Shell PLC",                     exchange: "NYSE",   sector: "Energy",   indices: ["ADR"] }],
  ["TTE",   { name: "TotalEnergies SE",               exchange: "NYSE",   sector: "Energy",   indices: ["ADR"] }],
  ["HSBC",  { name: "HSBC Holdings PLC",              exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["BBVA",  { name: "Banco Bilbao Vizcaya Argentaria",exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["UBS",   { name: "UBS Group AG",                  exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["CS",    { name: "Credit Suisse Group AG",         exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["DB",    { name: "Deutsche Bank AG",               exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["BCS",   { name: "Barclays PLC",                  exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["RY",    { name: "Royal Bank of Canada",           exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["TD",    { name: "Toronto-Dominion Bank",          exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["BNS",   { name: "Bank of Nova Scotia",            exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["CNQ",   { name: "Canadian Natural Resources Ltd.",exchange: "NYSE",   sector: "Energy",   indices: ["ADR"] }],
  ["SAN",   { name: "Banco Santander S.A.",           exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["INFY",  { name: "Infosys Limited",               exchange: "NYSE",   sector: "Tech",     indices: ["ADR"] }],
  ["WIT",   { name: "Wipro Limited",                 exchange: "NYSE",   sector: "Tech",     indices: ["ADR"] }],
  ["HDB",   { name: "HDFC Bank Limited",              exchange: "NYSE",   sector: "Finance",  indices: ["ADR"] }],
  ["VALE",  { name: "Vale S.A.",                     exchange: "NYSE",   sector: "Matls",    indices: ["ADR"] }],
  ["GOLD",  { name: "Barrick Gold Corporation",       exchange: "NYSE",   sector: "Matls",    indices: ["ADR"] }],
  ["ABX",   { name: "Barrick Gold Corporation",       exchange: "NYSE",   sector: "Matls",    indices: ["ADR"] }],
  ["NEM",   { name: "Newmont Corporation",            exchange: "NYSE",   sector: "Matls",    indices: ["SP500","ADR"] }],
  ["RIO",   { name: "Rio Tinto PLC",                 exchange: "NYSE",   sector: "Matls",    indices: ["ADR"] }],
  ["BHP",   { name: "BHP Group Limited",              exchange: "NYSE",   sector: "Matls",    indices: ["ADR"] }],
  ["KWEB",  { name: "KraneShares CSI China Internet", exchange: "NYSE",   sector: "Comm",     indices: ["ADR"] }],
  ["SE",    { name: "Sea Limited",                   exchange: "NYSE",   sector: "Comm",     indices: ["ADR"] }],
  ["GRAB",  { name: "Grab Holdings Limited",          exchange: "NASDAQ", sector: "Comm",     indices: ["ADR"] }],
  ["TCEHY", { name: "Tencent Holdings Ltd. (OTC)",    exchange: "OTC",    sector: "Comm",     indices: ["ADR"] }],
  ["MPNGY", { name: "mPay (Meituan) ADR",             exchange: "OTC",    sector: "Consumer", indices: ["ADR"] }],
];

// ─── Build lookup map ─────────────────────────────────────────────────────────

export const CATALOG: ReadonlyMap<string, CatalogEntry> = new Map(
  _entries
    .filter(([ticker]) => ticker.length > 0)
    .map(([ticker, info]) => [ticker, { ticker, ...info }] as const)
);

// ─── Index sets for browse ────────────────────────────────────────────────────

export const INDEX_LABELS: Record<string, string> = {
  SP500:    "S&P 500",
  NASDAQ100:"Nasdaq 100",
  DOW30:    "Dow Jones 30",
  ETF:      "ETFs",
  ADR:      "ADRs / Global",
};

export const SECTOR_LABELS: Record<string, string> = {
  Tech:     "Information Technology",
  Finance:  "Financials",
  Health:   "Health Care",
  Consumer: "Consumer Discretionary",
  Staples:  "Consumer Staples",
  Comm:     "Communication Services",
  Energy:   "Energy",
  Indust:   "Industrials",
  Matls:    "Materials",
  RealEst:  "Real Estate",
  Utility:  "Utilities",
  ETF:      "ETFs & Funds",
};

// All sectors, ordered
export const ALL_SECTOR_KEYS = Object.keys(SECTOR_LABELS);

// Get all entries for an index
export function getByIndex(index: string): CatalogEntry[] {
  const out: CatalogEntry[] = [];
  for (const entry of CATALOG.values()) {
    if (entry.indices.includes(index)) out.push(entry);
  }
  return out.sort((a, b) => a.ticker.localeCompare(b.ticker));
}

// Get all entries for a sector
export function getBySector(sector: string): CatalogEntry[] {
  const out: CatalogEntry[] = [];
  for (const entry of CATALOG.values()) {
    if (entry.sector === sector) out.push(entry);
  }
  return out.sort((a, b) => a.ticker.localeCompare(b.ticker));
}

// Search: returns up to `limit` matches ranked by relevance
export function searchCatalog(query: string, limit = 20): CatalogEntry[] {
  if (!query.trim()) return [];
  const upper = query.toUpperCase();

  const scored: { entry: CatalogEntry; score: number }[] = [];
  for (const entry of CATALOG.values()) {
    const t = entry.ticker.toUpperCase();
    const n = entry.name.toUpperCase();
    let score: number | null = null;

    if (t === upper)                           score = 0;
    else if (t.startsWith(upper))              score = 1;
    else if (n.startsWith(upper))              score = 2;
    else if (n.includes(upper) && upper.length >= 2) score = 3;

    if (score !== null) scored.push({ entry, score });
  }

  return scored
    .sort((a, b) => a.score - b.score || a.entry.ticker.localeCompare(b.entry.ticker))
    .slice(0, limit)
    .map(x => x.entry);
}

export const CATALOG_SIZE = _entries.length;
